name: Publish resume

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  pages: write
  id-token: write
  contents: read

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare files
        run: |
          mkdir artifacts
          cp resume.html artifacts/index.html
          cp resume.css artifacts/style.css

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './artifacts'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2