name: Publish resume to GitHub Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

# Allows changes published by token to write to pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Move and modify files ready for GitHub Pages
      - name: Prepare files
        run: |
          mkdir artifacts
          cp resume.html artifacts/index.html
          cp resume.css artifacts/style.css
          cp -r resources artifacts/resources
          
          cd artifacts
          sed -i 's/resume.css/style.css/g' index.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Upload everything from artifacts folder
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'artifacts'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Export resume.html to pdf
        uses: markwilson/html2pdf@v1.0
        with:
          htmlPath: 'resume.html'
          pdfName: 'resume'

      - name: Upload PDF
        id: upload
        uses: actions/upload-artifact@v4
        with:
          path: 'resume.pdf'
          name: 'Resume.pdf'

